### ISSUE TITLE
Update for Passport 7?

### ISSUE THREAD

**Issue by hackel** [ssmulders/hashed-passport#10]
What is the current status of this package?  I notice that there is a 6.0 branch, but master still depends on 5.0.  Passport is currently at version 7.1.  Is it still compatible?

Edit: Also, I tried to run the existing tests, but gave up.  Looks like they were pulled out of a Laravel project without setting up the required dependencies.  I see this was mentioned in #7, but all that does is change the composer dependency.  Without tests, it makes me nervous of any potential compatibility issues with later versions of Passport.

**Comment by ssmulders** [comment]
Thanks Ryan! I've merged your PR and added you as a collaborator. Feel free to add functionality, merge PRs and add tests! As mentioned in the other PR I'm swamped at the moment so your contribution is greatly appreciated :)
