### ISSUE TITLE
Why using hashid?

### ISSUE THREAD

**Issue by AmirrezaNasiri** [ssmulders/hashed-passport#12]
Hashid doesn't seem to be a good choice for this purpose since there are very well known methods to decrypt them without the salt. See "decoding without salt" section of [official docs](https://hashids.org/php/).

I know it's not a real security problem however by decrypting it, the main issue will still exist and that problem is from business perspective, knowing number of registered clients.

Using UUID would be a better solution. Any idea on this?

**Comment by hackel** [comment]
> Do you have a question or comment that involves "security" and "hashids" in the same sentence? Don't use Hashids.

The main purpose is to provide unique, non-integer IDs that are short and human-readable, and to prevent the ability of a user to easily guess the ID of the next record.  It is not designed to provide any actual security beyond plain integer IDs.  It functions as a drop-in replacement without actually touching the database.

The method described to recover the salt relies upon having access to the (salted) HashID function accepting an arbitrary input.  That is not the case here.  Knowing the number of client records isn't even useful without knowing how the application is structured.  Most allow multiple clients per user, let alone per company, etc. but it depends entirely on the particular app.

If you want UUIDs, just use UUIDs.  Or store proper cryptographic hashes in your DB.  That is not the purpose of this project.
