### ISSUE TITLE
Packagist differs from github repo's composer.json

### ISSUE THREAD

**Issue by onurkose** [ssmulders/hashed-passport#3]
dev-master / 1.1.x-dev requires laravel/passport: ^5.0 on packagist but current laravel/passport is 6.0 for newcomers.

**Comment by ssmulders** [comment]
Thanks for the heads-up! I hooked up packagist to this repo so it's auto-updated from now on. This is my first public repo so I appreciate the feedback.

Are things as you expect them to be now?

**Comment by ssmulders** [comment]
I just created a 6.0 and 5.0 branch and set the latter as default, similar to how the Passport repo is setup 😃

**Comment by onurkose** [comment]
> Are things as you expect them to be now?

Well, it should be good by now on packagist side. 
The result of being different on both sides used to make not easy to install your repo onto laravel/passport because of the version requirements. 
But there is a composer flag (--prefer-source) to workaround this, and I've already did that at the beginning.
Good repo after two years of discussion btw :) Thank you very much.

**Comment by onurkose** [comment]
But wait,
Where is enableEncrytion function? Apart from typo "enableEn**cry**tion", I can't find a function named neither enableEncrytion or enableEncryption in your source code. There is one withEncryption function though.

**Comment by ssmulders** [comment]
You're right it's `HashedPassport::withEncryption()` - fixed the readme just now 😄
