### ISSUE TITLE
Missing routes

### ISSUE THREAD

**Issue by satyago** [ssmulders/hashed-passport#5]
Hi @ssmulders, just FYI:
The provided route override does not cover enough grounds by default.

The following routes will have to be overwritten, so that the default JSON API to edit clients will work as well:

|Method|URI|Action|
|-|-|-|
|DELETE|oauth/clients/{client_id}|Laravel\Passport\Http\Controllers\ClientController@destroy|
|PUT|oauth/clients/{client_id}|Laravel\Passport\Http\Controllers\ClientController@update|

The problem however seems to be that the route parameter `client_id` is passed into the controller as the second argument. So overriding the request in the middleware doesn't work.
The middleware also adds the `client_id` to the request form even if not intended to be there, which then gets added to the query inside the `ClientController`.

**Comment by satyago** [comment]
Just noticed that you partially documented this in the readme.
Have you skipped those routes in fear of conflicting with package user customisations?

**Comment by ssmulders** [comment]
Hey @satyago! Is this a deal breaker for you? One possible solution could be to create two middlewares so you could pick and choose yourself? 

If you could make a suggestion that's 100% flexible and unobtrusive I'd be happy to implement it 😄 

The `hashed_passport` middleware is there specifically to overwrite any default Passport routes - so maybe that's enough.

**Comment by satyago** [comment]
@ssmulders Thank you for your time :-)

I've come to the decision that the ID format and its theoretical customisation options should be a concern of the Passport package. However, nothing has happened for quite a while in that regard and the opinions are divided. So I will try to extend that package should the need for hidden ID's grow. What you did is probably enough for most and any other work would indeed be too obtrusive …
