### ISSUE TITLE
InvalidArgumentException: Connection [hashed_passport] not configured.

### ISSUE THREAD

**Issue by charlizesmith** [ssmulders/hashed-passport#9]
Hello ,
My laravel version is 5.6 after installing your package I added below lines to my api.php

Route::post('/log', 'Mycontroller@login')->middleware(['hashed_passport']);

but I am getting below error - InvalidArgumentException: Connection [hashed_passport] not configured

**Comment by ssmulders** [comment]
Hi Charlize!

I think this has to do with Hashids. Have you verified the installation of it?

This is most likely where you're getting the error from:
https://github.com/ssmulders/hashed-passport/blob/5.0/src/Traits/HashesIds.php
